### ISSUE TITLE
Urgent: Operator Documentation Needs Work

### ISSUE THREAD

**Issue by mrhillsman** [IBM/ibm-monitoring-grafana-operator#41]
Hi, I work on the Red Hat Operator Enablement team and upon review of the operator we found the documentation to be lacking required information for successful use and experience of the end-user:

![01](https://user-images.githubusercontent.com/3989695/89920281-d52eb300-dbc1-11ea-9a5a-27fb754c3bf7.png)

An example of an operator taking advantage of various parts of the CSV which needs to be updated for the changes can be seen here:

![02](https://user-images.githubusercontent.com/3989695/89918659-eecefb00-dbbf-11ea-976e-dd793d2f1539.png)
![03](https://user-images.githubusercontent.com/3989695/89918661-ef679180-dbbf-11ea-9648-aba5825d6f39.png)

I have highlighted certain parts of the Couchbase operator which utilizes the CSVs ability to accept Markdown for the metadata; hyperlinks, (un)ordered lists, etc.

**Comment by dongwangdw** [comment]
@mrhillsman 
Thanks for the info.
I saw your version is 1.8.0. This is the very initial one.
The latest should be 1.9.2 and we have done a lot of doc work which follows our doc template.
![Screen Shot 2020-08-12 at 09 53 51](https://user-images.githubusercontent.com/2303377/89966447-c1e31c80-dc81-11ea-99c6-f8d03fbd8a48.png)

**Comment by dongwangdw** [comment]
I will close this. If any problem, please let me know and reopen.Thanks.
