### ISSUE TITLE
Question about this operator

### ISSUE THREAD

**Issue by pb82** [IBM/ibm-monitoring-grafana-operator#43]
Hey everyone,

was there a specific reason to create this operator instead of using the [existing one](https://github.com/integr8ly/grafana-operator) from the integr8ly project?

I'd be interested to learn if you are solving specific use cases that ours can't handle at the moment and if it would make sense to try to support them in our operator.

Thanks!

**Comment by dongwangdw** [comment]
@pb82 Hi Peter,

Yes, indeed, the integr8tly grafana operator exists before ours. And before our dev, we have evaluated it. And at last we did not take it for reasons:

1. We have our own dashboard crd and it is deployed by our internal adopters extensively. We want to break them.
2. grafana is not one of the components of our monitoring solution. And there are some couple components we have to consider. We have customized the rbac.

But the first one is the key point. 
Well with time,  the gap will be abridged. We intended to opensource our dashboard crd, but it is delayed. With operator now used heavily, we may not do that later, but maybe just conribute the idea to integra8tly dashboard.
